# Generated by Django 5.0.6 on 2024-07-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('MAT-TIC', 'Material de TIC'), ('MAT-EXPEDIENTE', 'Material de Expediente'), ('MAT-ESCRITORIO', 'Material de Escritório')], default='', max_length=100)),
                ('qtd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo', models.CharField(choices=[('UND', 'Unidade'), ('KG', 'Quilograma'), ('PCT', 'Pacote')], default='UND', max_length=100)),
            ],
        ),
    ]
