# Generated by Django 5.0.6 on 2024-07-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_material_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='qtd',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
    ]
