# Generated by Django 5.0.6 on 2024-07-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_material_qtd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='qtd',
            field=models.IntegerField(),
        ),
    ]
