# Generated by Django 5.0.6 on 2024-07-03 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
        ('estoque', '0003_alter_material_qtd'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='item',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='estoque.material'),
            preserve_default=False,
        ),
    ]
