# Generated by Django 5.0.6 on 2024-07-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0002_carrinho_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='qtd',
            field=models.IntegerField(),
        ),
    ]
